services:
  - type: web
    name: pswfabi
    runtime: node
    plan: free
    region: oregon
    branch: main
    repo: https://github.com/fabrizzio27/Proiect-Software.git
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: "20.18.1"
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
